### ISSUE TITLE
EndNet does not actually have an implementation

### ISSUE THREAD

**Issue by JMaravalhasSilva** [xiuheng-wang/awesome-hyperspectral-image-unmixing#2]
The readme mentions that code is available for the EndNet technique, but the actual "[code](https://github.com/savasozkan/endnet)" that the authors made available is not an actual implementation, it merely loads pre-calculated results and plots them.

This is misleading and a waste of time for anyone actually searching for available implementations of spectral unmixing techniques.

I'd suggest that the link be removed, or at the very least renamed from "code" to "results".

**Comment by xiuheng-wang** [comment]
Thank you for your feedback. To address your concerns, we have updated the link for EndNet in the README from "Code" to "Result". 
This should clarify that the provided resources are for loading and plotting pre-calculated results rather than a full implementation of the technique. 
We appreciate your contributions to this project and hope this adjustment will better meet the needs of those searching for spectral unmixing techniques.

**Comment by JMaravalhasSilva** [comment]
Now that I'm reading my post again, I realize that I came across as quite harsh. I apologize and thank you for the update. :)
